apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: trace-quickops
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Parsers_File  parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Parser        docker
        Tag           kube.*

    [FILTER]
        Name              kubernetes
        Match             kube.*
        Kube_URL          https://kubernetes.default.svc:443
        Kube_CA_File      /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File   /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log         On
        Keep_Log          Off
        Kube_Tag_Prefix   kube.var.log.containers.

    [OUTPUT]
        Name                    loki
        Match                   kube.*
        Host                    172.17.18.251
        Port                    3100
        Uri                     /loki/api/v1/push
        Labels                  job=$kubernetes['pod_name'],namespace=$kubernetes['namespace_name'],container=$kubernetes['container_name'],cluster="qaappk8s-local"
        auto_kubernetes_labels  True
        line_format             json

  parsers.conf: |
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
