entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

certificatesResolvers:
  cloudflare:
    acme:
      email: admin@kk.host #anyemail to get the certificate
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  docker:
    exposedByDefault: false
