workflow:
  rules:
    - when: always

include:
  - local: ".gitlab/ci-${CI_COMMIT_REF_NAME}.yaml"
    rules:
      - if: '$CI_COMMIT_REF_NAME == "stage" || $CI_COMMIT_REF_NAME == "qa" || $CI_COMMIT_REF_NAME == "uat" || $CI_COMMIT_REF_NAME == "prod"'
        exists:
          - ".gitlab/ci-${CI_COMMIT_REF_NAME}.yaml"

  - local: ".gitlab/ci-default.yaml"
    rules:
      - if: '$CI_COMMIT_REF_NAME != "stage" && $CI_COMMIT_REF_NAME != "qa" && $CI_COMMIT_REF_NAME != "uat" && $CI_COMMIT_REF_NAME != "prod"'
        exists:
          - ".gitlab/ci-default.yaml"
