global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

rule_files:
   - "rules/node_rules.yml"
   - "rules/container_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
  - job_name: 'hypervisors'
    file_sd_configs:
      - files:
          - '/opt/prometheus/files_sd/local_hypervisors.yml'
    scheme: https
    metrics_path: '/pve'
    params:
      cluster: ['1']
      node: ['1']
    basic_auth:
      username: 'aesmonitor'
      password: 'UdnBf00R@z06'
    tls_config:
      ca_file: '/opt/prometheus/ssl/node_exporter.crt'
      insecure_skip_verify: true
    relabel_configs:
      - source_labels: ['target_name']
        target_label: 'target_name'
      - source_labels: ['__address__']
        regex: '([^:]+)(?::\d+)?'
        replacement: '$1'
        target_label: '__param_target'
      - source_labels: ['__param_target']
        target_label: 'instance'
