- name: Scale up backend replicas
  kubernetes.core.k8s_scale:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ namespace }}"
    api_version: "{{ apiversion }}"
    kind: "{{ crds }}"
    name: "{{ deployment }}"
    replicas: "{{ replicas | int }}"
    wait: true
    wait_timeout: 300
    wait_sleep: 10 