---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
      - lsb-release
      - python3-pip
      - python3-setuptools
      - jq
      - socat
      - conntrack
      - ipset
    state: present
  become: yes

- name: Disable swap
  command: swapoff -a
  become: yes
  ignore_errors: yes

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*swap.*'
    state: absent
  become: yes

- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  become: yes

- name: Configure sysctl for Kubernetes
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  become: yes
  loop:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.ipv4.conf.all.rp_filter', value: '1' }
    - { name: 'net.ipv4.conf.default.rp_filter', value: '1' }

- name: Create Kubernetes directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  become: yes
  loop:
    - /etc/kubernetes
    - /etc/kubernetes/manifests
    - /etc/kubernetes/pki
    - /var/lib/kubelet
    - /var/lib/kubernetes
    - /opt/cni/bin
    - /etc/cni/net.d

- name: Install containerd
  apt:
    name: containerd
    state: present
  become: yes

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'
  become: yes

- name: Generate containerd config
  command: containerd config default
  register: containerd_config
  become: yes

- name: Write containerd config
  copy:
    content: "{{ containerd_config.stdout }}"
    dest: /etc/containerd/config.toml
  become: yes

- name: Configure containerd systemd cgroup driver
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup ='
    line: '            SystemdCgroup = true'
  become: yes

- name: Enable and restart containerd
  systemd:
    name: containerd
    enabled: yes
    state: restarted
  become: yes

- name: Add Kubernetes apt repository key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version.split('.')[0] }}-{{ kubernetes_version.split('.')[1] }}/deb/Release.key
    state: present
  become: yes

- name: Add Kubernetes apt repository
  apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version.split('.')[0] }}-{{ kubernetes_version.split('.')[1] }}/deb/ /"
    state: present
    filename: kubernetes
  become: yes

- name: Install Kubernetes packages
  apt:
    name:
      - "kubelet={{ kubernetes_version }}-00"
      - "kubeadm={{ kubernetes_version }}-00"
      - "kubectl={{ kubernetes_version }}-00"
    state: present
    hold: yes
  become: yes

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started
  become: yes

- name: Create kubelet config directory
  file:
    path: /etc/systemd/system/kubelet.service.d
    state: directory
    mode: '0755'
  become: yes