---
- name: Configure sysctl parameters for Kubernetes
  hosts: all
  gather_facts: false 
  become: yes
  pre_tasks:
  - name: Create k8s.conf file
    ansible.builtin.copy:
      content: |
        overlay
        br_netfilter
      dest: /etc/modules-load.d/k8s.conf

  - name: Load kernel modules
    ansible.builtin.command:
      cmd: modprobe {{ item }}
    loop:
      - br_netfilter
      - overlay
      
  tasks:
    - name: Ensure Kubernetes sysctl configuration is present
      become: yes
      lineinfile:
        path: /etc/sysctl.d/k8s.conf
        create: yes
        line: "{{ item }}"
      loop:
        - "net.bridge.bridge-nf-call-iptables  = 1"
        - "net.bridge.bridge-nf-call-ip6tables = 1"
        - "net.ipv4.ip_forward                 = 1"

      notify: Apply sysctl settings
  
  handlers:
    - name: Apply sysctl settings
      command: sysctl --system
