---
- hosts: masters
  become: true
  gather_facts: true
  tasks:
    - name: Ensure $HOME/.kube directory exists
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'

    - name: Copy Kubernetes admin.conf to user's kube config
      command: cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
    - name: Change ownership of the kube config file
      file:
        path: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0644'
