---
- name: Install and configure NFS, iSCSI, cryptsetup, NFS-Client, and dmsetup
  hosts: all
  become: true 

  tasks:

    - name: Install open-iscsi
      ansible.builtin.apt:
        name: open-iscsi
        state: present
        update_cache: yes
      retries: 10
      delay: 15
      register: result
      until: result is success

    - name: Load iscsi_tcp module
      ansible.builtin.command:
        cmd: modprobe iscsi_tcp
      # when: ansible_facts['os_family'] == "Debian"

    - name: Install cryptsetup
      ansible.builtin.apt:
        name: cryptsetup
        state: present
        update_cache: yes
      retries: 10
      delay: 15
      register: result
      until: result is success

    - name: Install dmsetup
      ansible.builtin.apt:
        name: dmsetup
        state: present
        update_cache: yes
      retries: 10
      delay: 15
      register: result
      until: result is success

    - name: Ensure iscsi service is started
      ansible.builtin.service:
        name: iscsid
        state: started
        enabled: yes
        
    - name: install nfs-common
      ansible.builtin.apt:
        name: nfs-common
        state: latest
      retries: 10
      delay: 15
      register: result
      until: result is success

