---
- hosts: all
  become: true
  gather_facts: false 
  tasks:
  - name: install nfs-common
    ansible.builtin.apt:
      name: nfs-common
      state: latest
      # update_cache: true
- hosts: masters
  become: true
  gather_facts: false 
  tasks:
  - name: helm install
    community.general.snap:
      name: helm
      classic: true
  - name: helm nfs repo add
    become: false
    command: helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
 

  - name: helm nfs install
    become: false
    command: helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --set nfs.server={{ nfs_server }} --set nfs.path={{ nfs_path }}
    ignore_errors: true
