Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
      master.vm.box = "ubuntu/bionic64"
      master.vm.hostname = "master"
      master.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-master"
        vb.memory = "4096"
        vb.cpus = 4
      end
      master.vm.network "private_network", ip: "192.168.56.10"
    end
  
    config.vm.define "worker1" do |worker1|
      worker1.vm.box = "ubuntu/bionic64"
      worker1.vm.hostname = "worker1"
      worker1.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-worker1"
        vb.memory = "6144"
        vb.cpus = 4
      end
      worker1.vm.network "private_network", ip: "192.168.56.11"
    end
    
    config.vm.define "worker2" do |worker2|
      worker2.vm.box = "ubuntu/bionic64"
      worker2.vm.hostname = "worker2"
      worker2.vm.provider "virtualbox" do |vb|
        vb.name = "k8s-worker2"
        vb.memory = "6144"
        vb.cpus = 4
      end
      worker2.vm.network "private_network", ip: "192.168.56.12"
    end
  end
  