# values-cp.yaml
ingressController:
  enabled: false

image:
  repository: kong/kong-gateway
  tag: "3.12"

secretVolumes:
  - kong-cluster-cert

env:
  role: control_plane
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  database: postgres
  pg_database: kong
  pg_user: kong_admin
  pg_password: "kongPass1234"
  pg_host: kong-postgres.kong.svc.cluster.local
  # pg_ssl: "on"
  # pg_ssl_version: "tlsv1_3"
  admin_gui_auth: basic-auth
  enforce_rbac: "on"
  admin_gui_session_conf: |
      {
        "secret": "eXTa4rOTPeXdiUTzryQzyCpYU2OrNm+Mf/GiRe/kVdY=",
        "cookie_name": "kong_admin_session",
        "cookie_secure": true,
        "cookie_same_site": "Lax",
        "storage": "kong",
        "cookie_lifetime": 3600,
        "cookie_renew": 600
      }
  password: "kong"
  enterprise:
    enabled: true
    license_secret: kong-enterprise-license

admin:
  enabled: true
  http:
    enabled: true

cluster:
  enabled: true
  tls:
    enabled: true

clustertelemetry:
  enabled: true
  tls:
    enabled: true

manager:
  enabled: false

proxy:
  enabled: false