global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

rule_files:
   - "rules/node_rules.yml"
   - "rules/container_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"
          
  - job_name: 'blackbox'
    metrics_path: /probe
    scheme: https
    basic_auth:
      username: 'aesmonitor'
      password: 'UdnBf00R@z06'
    tls_config:
      ca_file: '/opt/prometheus/ssl/node_exporter.crt'
      insecure_skip_verify: true
    file_sd_configs:
      - files:
          - '/opt/prometheus/files_sd/blackbox_targets.yml'
    params:
      module: [http_2xx]  
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 172.17.17.239:9115