apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql 
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin
    general_log=1
    general_log-file=/var/log/mysql/mysql.log
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    super-read-only    
    general_log=1
    general_log-file=/var/log/mysql/mysql.log

  