FROM openjdk:22 AS builder
WORKDIR /app

ENV MAVEN_OPTS="-Dmaven.wagon.http.ssl.insecure=true \
-Dmaven.wagon.http.ssl.allowall=true \
-Dmaven.wagon.http.ssl.ignore.validity.dates=true \
-Dmaven.resolver.transport=wagon"

COPY ./nexus-artifacthub/settings-docker.xml /root/.m2/settings.xml
COPY . .
# COPY ./src/main/resources/application-dev.properties ./src/main/resources/application.properties

ARG NEXUS_USER \ 
    NEXUS_PASS

RUN chmod +x mvnw && \
./mvnw dependency:go-offline -s /root/.m2/settings.xml -Pdev && \
./mvnw clean package -DskipTests -s /root/.m2/settings.xml -Pdev

# #FROM ghcr.io/graalvm/jdk-community:22
FROM openjdk:22
WORKDIR /app
RUN rm /etc/localtime && \
    ln -s /usr/share/zoneinfo/Asia/Dhaka /etc/localtime && \
    curl -sSL \
    https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar \
    -o /opt/opentelemetry-javaagent.jar
COPY --from=builder /app/target/*.jar app.jar
# RUN groupadd -g 1001 appgroup && \
#     useradd -u 1001 -g appgroup -m appuser && \
#     chown -R appuser:appgroup /app
# RUN rm -f /bin/sh
# USER appuser

EXPOSE 8082 5583

# CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5583", "-jar", "app.jar"]
CMD ["sh", "-c", "\
  java \
    -javaagent:/opt/opentelemetry-javaagent.jar \
    -Dotel.traces.exporter=otlp \
    -Dotel.metrics.exporter=otlp \
    -Dotel.logs.exporter=otlp \
    -Dotel.exporter.otlp.endpoint=http://172.17.17.252:4317 \
    -Dotel.exporter.otlp.protocol=grpc \
    -Dotel.sampler.probability=1.0 \
    -Dotel.resource.attributes=service.name=${SERVICE_NAME:-dev-quickopsbe} \
    -Dotel.instrumentation.jdbc-datasource.enabled=true \
    -Dotel.instrumentation.hikaricp.enabled=true \
    -Dotel.instrumentation.spring-data.enabled=true \
    -Dotel.instrumentation.jdbc.statement-sanitizer.enabled=true \
    -Dotel.instrumentation.logback-appender.enabled=true \
    -Dotel.instrumentation.jdbc.experimental-span-attributes=true \
    -Dotel.instrumentation.spring-jdbc.enabled=true \
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5583 \
    -jar app.jar"]
