apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: orgpod
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: orgpod
    control-plane: controller-manager
    namespace: {{ default "aescloud-engine" .Release.Namespace }}
  name: aescloud-engine-controller-manager-metrics-service
  namespace: {{ default "aescloud-engine" .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager