---
- name: Check if cluster is already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_init_file

- name: Initialize Kubernetes cluster on first master
  command: >
    kubeadm init
    --control-plane-endpoint="{{ control_plane_endpoint }}"
    --pod-network-cidr="{{ pod_network_cidr }}"
    --service-cidr="{{ service_network_cidr }}"
    --kubernetes-version="{{ kubernetes_version }}.0"
    --upload-certs
    --apiserver-advertise-address="{{ ansible_host }}"
    --ignore-preflight-errors=Swap
  become: yes
  when: inventory_hostname == groups['masters'][0] and not kubeadm_init_file.stat.exists
  register: kubeadm_init

- name: Create .kube directory
  file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0755'
  become: yes
  when: inventory_hostname == groups['masters'][0]

- name: Copy kubeconfig to user home
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    remote_src: yes
  become: yes
  when: inventory_hostname == groups['masters'][0]

- name: Get join command for masters
  command: kubeadm token create --print-join-command
  register: join_command
  when: inventory_hostname == groups['masters'][0]
  changed_when: false

- name: Get certificate key
  command: kubeadm init phase upload-certs --upload-certs
  register: certificate_key
  when: inventory_hostname == groups['masters'][0]
  changed_when: false

- name: Set join command and certificate key facts
  set_fact:
    master_join_command: "{{ join_command.stdout }}"
    master_certificate_key: "{{ certificate_key.stdout_lines[-1] }}"
  when: inventory_hostname == groups['masters'][0]

- name: Join additional masters to cluster
  command: >
    {{ hostvars[groups['masters'][0]]['master_join_command'] }}
    --control-plane
    --certificate-key {{ hostvars[groups['masters'][0]]['master_certificate_key'] }}
  become: yes
  when: inventory_hostname != groups['masters'][0] and not kubeadm_init_file.stat.exists
  register: master_join

- name: Wait for API server to be ready
  uri:
    url: https://127.0.0.1:6443/healthz
    method: GET
    validate_certs: no
  register: api_health
  until: api_health.status == 200
  retries: 30
  delay: 10
  when: kubeadm_init.changed or master_join.changed

- name: Get join command for workers
  command: kubeadm token create --print-join-command
  register: worker_join_command
  delegate_to: "{{ groups['masters'][0] }}"
  changed_when: false

- name: Set worker join command fact
  set_fact:
    worker_join_command: "{{ worker_join_command.stdout }}"
  delegate_to: "{{ groups['masters'][0] }}"
  delegate_facts: yes