apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
    #toleration is for selcting master nodes controlplane logs as well
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      serviceAccount: fluentd
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        #image: fluent/fluentd-kubernetes-daemonset:v1.4.2-debian-elasticsearch-1.1
        image: fluent/fluentd-kubernetes-daemonset:v1.16.2-debian-elasticsearch7-1.0

        env:
          - name:  FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch.default.svc.cluster.local"
          - name:  FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          # - name: FLUENTD_ARGS
          #   value: --no-supervisor -q


        volumeMounts:
        - name: fluentd-base-cm
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: fluentd-org-cm
          mountPath: /fluentd/etc/org-log.conf
          subPath: org-log.conf
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: fluentd-org-cm
        configMap:
          name: fluentd-org-cm
      - name: fluentd-base-cm
        configMap:
          name: fluentd-base-cm
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
