apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-configmap
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"

    admin_variables=
    {
        admin_credentials="admin:admin;cluster:secret"
        mysql_ifaces="0.0.0.0:6032"
        refresh_interval=2000
        cluster_username="cluster"
        cluster_password="secret"  
    }

    mysql_variables=
    {
        threads=4
        max_connections=2048
        default_query_delay=0
        default_query_timeout=36000000
        have_compress=true
        poll_timeout=2000
        interfaces="0.0.0.0:6033;/tmp/proxysql.sock"
        default_schema="information_schema"
        stacksize=1048576
        server_version="8.0.23"
        connect_timeout_server=3000
        monitor_username="monitor"
        monitor_password="monitor"
        monitor_history=600000
        monitor_connect_interval=60000
        monitor_ping_interval=10000
        monitor_read_only_interval=1500
        monitor_read_only_timeout=500
        ping_interval_server_msec=120000
        ping_timeout_server=500
        commands_stats=true
        sessions_sort=true
        connect_retries_on_failure=10
    }

    mysql_servers =
    (
        { address="mysql-read" , port=3306 , hostgroup=10, max_connections=100 },
        { address="mysql-0.mysql" , port=3306 , hostgroup=20, max_connections=100 } #hostgrp 20 = master
    )

    mysql_users =
    (
        { username = "akif", password = "password", default_hostgroup = 20, active = 1 }
    )



    mysql_query_rules =
    (
    
    
            # ALL THE DATABASE, TABLE, SCHEMA MANIPULATION COMMANDS----> MASTER(20)
            {
                    rule_id=100
                    active=1
                    match_pattern="^(CREATE|ALTER|DROP|ALTER|TRUNCATE|RENAME|MERGE|INSERT|REPLACE|DELETE|LOAD|CALL|SET) .*$"
                    destination_hostgroup=20
                    apply=1
            },

            # LOCK TABLE FOR UPDATE ----------------------------------> MASTER(20)
            {
                    rule_id=200
                    active=1
                    match_pattern="^SELECT .* FOR UPDATE"
                    destination_hostgroup=20
                    apply=1
            },
            # ALL OTHER READS   ----------------------------------------> SLAVE(10)
            {
                    rule_id=300
                    active=1
                    match_pattern="^(SELECT|SHOW|DESCRIBE|EXPLAIN) .*"
                    destination_hostgroup=10
                    apply=1
            },

    )


