apiVersion: v1
kind: Secret
metadata:
 name: user1-apikey              # Must match name referenced in KongConsumer
 namespace: grade-demo
 labels:
   konghq.com/credential: key-auth
type: Opaque
stringData:
 kongCredType: key-auth
 key: your-secret-key 