FROM node:22 AS builder
WORKDIR /app 
COPY . .
RUN npm install -g pnpm
RUN pnpm install --force && \
    pnpm run build


FROM nginx:1.27.0-alpine-slim 
COPY --from=builder /app/public /var/www/html/public
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
