vpc_cidr            = "10.0.0.0/16"
vpc_name            = "hecker-vpc"
private_subnet_cidrs = ["10.0.1.0/24", "10.0.2.0/24"]
public_subnet_cidr  = ["10.0.3.0/24"]
availability_zone   = ["ap-south-1a", "ap-south-1b"]
allowed_ssh_cidrs   = ["0.0.0.0/0"]
bucket_name         = "ec2-application-bucket"
ami_id              = "ami-053b12d3152c0cc71"
instance_type       = "t2.micro"
instance_name       = "ec2withs3-instance"
region              = "ap-south-1"
rds_allocated_storage = 20
rds_engine            = "mysql"
rds_engine_version    = "8.0.39"
rds_instance_class    = "db.t3.micro"
rds_db_name           = "mydb"
rds_username          = "admin"
rds_password          = "Aes1234!"
rds_skip_final_snapshot = true
