{
 "title": "Kubernetes Clusters StatefulSets Stats",
 "description": "Simple dashboard for observing your Kubernetes Statefulset CPU and Memory usage.",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "statefulset",
    "query": {
     "query": "label_values(kube_statefulset_status_replicas{namespace=\"$namespace\"},statefulset)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$statefulset.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU and Memory Usage Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "All pods CPU usage combined for selected statefulset",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "$statefulset - limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "$statefulset  - request"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$statefulset.*\"}[$__rate_interval])) by (statefulset)",
     "legendFormat": "$statefulset  - usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "All pods memory usage combined for selected statefulset",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "$statefulset - limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "$statefulset  - request"
    },
    {
     "expr": "max(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "$statefulset  - usage"
    }
   ]
  },
  {
   "title": "Pod Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{cluster=\"$cluster\", namespace=\"$namespace\", statefulset=\"$statefulset\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Desired Pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_statefulset_replicas{\n  cluster=\"$cluster\",\n  namespace=\"$namespace\",\n  statefulset=~\"${statefulset:regex}\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable Pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  kube_statefulset_replicas{cluster=\"$cluster\", namespace=\"$namespace\", statefulset=~\"${statefulset:regex}\"}\n  -\n  kube_statefulset_status_replicas_ready{cluster=\"$cluster\", namespace=\"$namespace\", statefulset=~\"${statefulset:regex}\"}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods Resource Usage - $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "pod" },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "All pods CPU usage combined for selected statefulset",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod - limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod  - request"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$pod.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "$pod  - usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "All pods memory usage combined for selected statefulset",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod - limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod  - request"
    },
    {
     "expr": "max(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod  - usage"
    }
   ]
  }
 ]
}