{
 "title": "Kubernetes Clusters",
 "description": "【English version】2025.01.25 Updates，kubernetesComprehensive display of resources！Includes K8S Overall Resource Overview、Microservices Resource Details、Pod Resource Details andK8SNetwork Bandwidth，Optimization metrics。https://grafana.com/orgs/starsliao/dashboards",
 "tags": [
  "Prometheus",
  "Kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Clusters",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "Node",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info{cluster=~\"$origin_prometheus\"},node)"
    }
   },
   {
    "name": "NameSpace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=~\"$origin_prometheus\"},namespace)"
    }
   },
   {
    "name": "Container",
    "label": "Microservice (Container Name)",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=~\"$origin_prometheus\", namespace=~\"$NameSpace\"},container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_status_ready{cluster=\"$origin_prometheus\", namespace=\"$NameSpace\", condition=\"true\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Resource Overview：SelectedPod:【$Pod】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "$Node：Pod Resource Detail(Associable Nodes)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace) / (sum(container_spec_cpu_quota{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}/100000) by (container, pod,node,namespace)) "
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace)",
     "legendFormat": "CPUKernel Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "wss%"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "wss"
    },
    {
     "expr": "sum (container_memory_rss{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "rss%"
    },
    {
     "expr": "sum (container_memory_rss{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"} * on (pod) group_left(node) kube_pod_info{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}"
    },
    {
     "expr": "time() - kube_pod_created{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"} * on(pod) group_right kube_pod_container_info{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_fs_limit_bytes{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(sum(irate(container_network_receive_bytes_total{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(irate(container_network_transmit_bytes_total{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Containers CPU Utilization (Maximum100%Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg(rate(container_cpu_usage_seconds_total{\n  pod=~\"^$Pod$\",\n  container!~\"^$|POD$\",\n  cluster=~\"$origin_prometheus\",\n  namespace=~\"$NameSpace\"\n}[5m])) by (namespace, pod)\n/\navg(kube_pod_container_resource_limits{resource=\"cpu\", namespace=~\"$NameSpace\", pod=~\"^$Pod$\"}) by (namespace, pod)\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Container Memory Usage (Associatable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (namespace, pod, container) (\n  container_memory_working_set_bytes{\n    cluster=~\"$origin_prometheus\",\n    namespace=~\"$NameSpace\",\n    pod=~\"$Pod\",\n    node=~\"$Node\",\n    container!~\"^$|POD$\"\n  }\n) / 1000000000\n",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max (container_memory_rss{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container=~\"$Container\",container!=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)\n/\nmax (container_spec_memory_limit_bytes{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container=~\"$Container\",container!=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"} or vector(1e9)) by (container, pod)\n* 100\n",
     "legendFormat": "RSS：{{ pod }}"
    },
    {
     "expr": "(\n  cass_jvm_heap{service=~\"$Container\"}\n  * on (pod_ip) group_right(service)\n  kube_pod_info{cluster=~\"$origin_prometheus\", pod=~\"$Pod\", namespace=~\"$NameSpace\"}\n)\n/\n(\n  cass_jvm_heap_max{service=~\"$Container\"}\n  * on (pod_ip) group_right(service)\n  kube_pod_info{cluster=~\"$origin_prometheus\", pod=~\"$Pod\", namespace=~\"$NameSpace\"}\n)\n* 100\n",
     "legendFormat": "Heap：{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Network bandwidth per second (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "max(max(irate(container_network_receive_bytes_total{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "Inflow:{{ pod}}"
    },
    {
     "expr": "max(max(irate(container_network_transmit_bytes_total{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "Outflow:{{ pod}}"
    }
   ]
  },
  {
   "title": "Pod Containers CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace)",
     "legendFormat": "CPU Usage：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "Pod CPU Limitations：{{ container}}"
    }
   ]
  },
  {
   "title": "Pod Containers WSS Memory Usage (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "PodMemory Limits：{{ container}}"
    }
   ]
  },
  {
   "title": "Pod Containers RSS Memory Usage (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_rss{cluster=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "RSS：{{ pod }}"
    }
   ]
  },
  {
   "title": "PVC",
   "type": "timeseries",
   "description": "PVC information ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max by (namespace, persistentvolumeclaim) (\n  label_replace(\n    kubelet_volume_stats_used_bytes{\n      cluster=~\"$origin_prometheus\",\n      namespace=~\"$NameSpace\"\n    } / (1024 * 1024 * 1024),\n    \"metric\", \"used_gb\", \"\", \"\"\n  )\n)\nor\nmax by (namespace, persistentvolumeclaim) (\n  label_replace(\n    kubelet_volume_stats_capacity_bytes{\n      cluster=~\"$origin_prometheus\",\n      namespace=~\"$NameSpace\"\n    } / (1024 * 1024 * 1024),\n    \"metric\", \"capacity_gb\", \"\", \"\"\n  )\n)\nor\nmax by (namespace, persistentvolumeclaim) (\n  label_replace(\n    (\n      kubelet_volume_stats_used_bytes{\n        cluster=~\"$origin_prometheus\",\n        namespace=~\"$NameSpace\"\n      }\n      /\n      kubelet_volume_stats_capacity_bytes{\n        cluster=~\"$origin_prometheus\",\n        namespace=~\"$NameSpace\"\n      }\n    ) * 100,\n    \"metric\", \"usage_percent\", \"\", \"\"\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Resource Overview：Selected Nodes:【$Node】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Memory Ratio",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 11, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",container!=\"\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "Memory Utilization"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "Memory Request Rate"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "Memory Limit Rate"
      }
     ]
    },
    {
     "title": "Namespace Resource Statistics",
     "type": "table",
     "gridPos": { "h": 9, "w": 5, "x": 11, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_pod_info{cluster=~\"$origin_prometheus\",node=~\"^$Node$\"}) by (namespace)"
      },
      {
       "expr": "count(kube_service_info{cluster=~\"$origin_prometheus\"}) by(namespace)"
      },
      {
       "expr": "count by (namespace)({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\",cluster=~\"$origin_prometheus\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count(kube_configmap_info{cluster=~\"$origin_prometheus\"}) by(namespace)",
       "legendFormat": "configmap"
      },
      {
       "expr": "count(kube_secret_info{cluster=~\"$origin_prometheus\"}) by(namespace)",
       "legendFormat": "secret"
      }
     ]
    },
    {
     "title": "$NameSpace：Network Overview（Associable nodes and namespaces）",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum (irate(container_network_receive_bytes_total{cluster=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum (irate(container_network_transmit_bytes_total{cluster=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
       "legendFormat": "Send"
      }
     ]
    },
    {
     "title": "Node Memory Information",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 11, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",container!=\"\",node=~\"^$Node$\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
       "legendFormat": "Limits"
      }
     ]
    },
    {
     "title": "Node CPU Ratio",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",container!=\"\",node=~\"^$Node$\"}[2m])) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "CPU Utilization Rate"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "CPU Request Rate"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "CPU Limit Rate"
      }
     ]
    },
    {
     "title": "Nodes with Pod",
     "type": "bargauge",
     "description": "Number of cluster nodes，Nodes POD Number of，NodesPODUpper Limit",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kube_node_info{cluster=~\"$origin_prometheus\"})",
       "legendFormat": "Number of nodes"
      },
      {
       "expr": "count(kube_pod_info{cluster=~\"$origin_prometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
       "legendFormat": "Pod Number of nodes"
      },
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})",
       "legendFormat": "Upper limit Pod"
      }
     ]
    },
    {
     "title": "Node CPU Number of cores",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "Total Cores"
      },
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}[2m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Node Storage Information",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(node_filesystem_size_bytes{cluster=~\"$origin_prometheus\", device=~\"^/dev/.*$\", node=~\"$Node\"}) - sum(node_filesystem_avail_bytes{cluster=~\"$origin_prometheus\", device=~\"^/dev/.*$\", node=~\"$Node\"})\n  / sum(node_filesystem_size_bytes{cluster=~\"$origin_prometheus\", device=~\"^/dev/.*$\", node=~\"$Node\"})",
       "legendFormat": "Utilization Rate"
      },
      {
       "expr": "sum(node_filesystem_size_bytes{cluster=~\"$origin_prometheus\", device=~\"^/dev/.*$\", node=~\"$Node\"})\n  - sum(node_filesystem_avail_bytes{cluster=~\"$origin_prometheus\", device=~\"^/dev/.*$\", node=~\"$Node\"})\n",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(node_filesystem_size_bytes{cluster=~\"$origin_prometheus\", device=~\"^/dev/.*$\", node=~\"$Node\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 138 },
     "repeat": "origin_prometheus",
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\",cluster=~\"$origin_prometheus\"})",
       "legendFormat": "Workload"
      },
      {
       "expr": "count(kube_pod_info{cluster=~\"$origin_prometheus\"})",
       "legendFormat": "Total Pod"
      },
      {
       "expr": "count by(key,origin_prometheus)(kube_node_spec_taint{cluster=~\"$origin_prometheus\",key=~\"node.kubernetes.io.*\"})",
       "legendFormat": "{{key}}"
      },
      {
       "expr": "count by(origin_prometheus)(kube_node_info{cluster=~\"$origin_prometheus\"})",
       "legendFormat": "Total Nodes"
      },
      {
       "expr": "count by(origin_prometheus)(kube_node_info{cluster=~\"$origin_prometheus\"}) - count by(origin_prometheus)(kube_node_spec_taint{cluster=~\"$origin_prometheus\",key!~\"node.kubernetes.io.*\"})",
       "legendFormat": "Normal Node"
      },
      {
       "expr": "count by(key,origin_prometheus)(kube_node_spec_taint{cluster=~\"$origin_prometheus\",key!~\"node.kubernetes.io.*\"})",
       "legendFormat": "{{key}}"
      }
     ]
    },
    {
     "title": "Memory Usage【$Node】",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
       "legendFormat": "Total Memory"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",container!=\"\",node=~\"^$Node$\"})",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "CPU Used Cores【$Node】",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
       "legendFormat": "Total Cores"
      },
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}[2m]))",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
       "legendFormat": "Requests"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Pod Number and nodes【$Node】",
     "type": "timeseries",
     "description": "Number of Cluster Nodes，Nodes POD Number of，Nodes POD Upper Limit",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_node_info{cluster=~\"$origin_prometheus\"})",
       "legendFormat": "Number of nodes"
      },
      {
       "expr": "count(kube_pod_info{cluster=~\"$origin_prometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
       "legendFormat": "Pod Number"
      },
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})",
       "legendFormat": "Upper Limit Pod"
      }
     ]
    },
    {
     "title": "$Node：Nodes CPU Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)*100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "$Node：Node Memory Breakdown",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",container!=\"\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)*100",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "$Node：Node Network Overview",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum (irate(container_network_receive_bytes_total{cluster=~\"$origin_prometheus\",node=~\"^$Node$\"}[2m]))by (node) *8",
       "legendFormat": "Inflow:{{node}}"
      },
      {
       "expr": "sum (irate(container_network_transmit_bytes_total{cluster=~\"$origin_prometheus\",node=~\"^$Node$\"}[2m]))by (node) *8",
       "legendFormat": "Outflows:{{node}}"
      }
     ]
    },
    {
     "title": "$Node：Node Information Detail",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 151 },
     "targets": [
      {
       "expr": "count(kube_pod_info{cluster=~\"$origin_prometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"}) by (node)",
       "legendFormat": "pod Number"
      },
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",container!=\"\",node=~\"^$Node$\"}[2m])) by (node)"
      },
      {
       "expr": "kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"} - 0"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",container!=\"\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"}) by (node) - 0"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_fs_usage_bytes{cluster=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_fs_limit_bytes{cluster=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",container!=\"\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "Memory Usage%"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "Memory Requests%"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "Memory Limit%"
      },
      {
       "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "CPU Usage%"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "CPU Requests%"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "Memory Limit%"
      },
      {
       "expr": "sum (container_fs_usage_bytes{cluster=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node) / sum (container_fs_limit_bytes{cluster=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node)",
       "legendFormat": "Disk Usage%"
      },
      {
       "expr": "sum(kube_node_status_allocatable{cluster=~\"$origin_prometheus\",resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})by (node)",
       "legendFormat": "PodCaps"
      }
     ]
    },
    {
     "title": "PVC Storage Usage",
     "type": "table",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$origin_prometheus\"})",
       "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
      },
      {
       "expr": "min by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=~\"$origin_prometheus\"}) + max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$origin_prometheus\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$origin_prometheus\"}) /(min by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=~\"$origin_prometheus\"}) + max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$origin_prometheus\"}))*100",
       "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
      },
      {
       "expr": "count by (namespace,persistentvolumeclaim)(kube_pod_spec_volumes_persistentvolumeclaims_info{cluster=~\"$origin_prometheus\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Namespaces CPU Usage kernel(>0.5)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 6, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",container !=\"\",container!=\"POD\"}[2m])) by (namespace)>0.5",
       "legendFormat": "{{ namespace }}"
      }
     ]
    },
    {
     "title": "Namespaces WSS Memory Usage (>1G)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",container !=\"\",container!=\"POD\"}) by (namespace) > 1*1024*1024*1024",
       "legendFormat": "{{namespace} {{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Microservices (Container Name) Resource Overview：Selected Microservices:【$Container】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Microservices (Container Name) Resource Statistics",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 198 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container))"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)",
       "legendFormat": "Total Cores Used"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_rss{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "Average Memory%(RSS)"
      },
      {
       "expr": "sum (container_memory_rss{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "Total Memory Usage (RSS) "
      },
      {
       "expr": "sum by(container) (kube_pod_container_resource_requests{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"})"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$origin_prometheus\",resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "avg(container_fs_usage_bytes{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "count(kube_pod_container_info{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container,namespace)"
      },
      {
       "expr": "avg(container_fs_limit_bytes{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      }
     ]
    },
    {
     "title": "Microservices (Container Name) Average CPU Usage (Maximum100%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 207 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container)) * 100",
       "legendFormat": "{{ container}}"
      }
     ]
    },
    {
     "title": "Microservice (Container Name) Average Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 207 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{cluster=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
       "legendFormat": "RSS：{{ container }}"
      }
     ]
    },
    {
     "title": "Microservice (Container Name) Network bandwidth per second (Associable Nodes)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 207 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "sum(sum(irate(container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(container) *8",
       "legendFormat": "Inflow:{{ container }}"
      },
      {
       "expr": "sum(sum(irate(container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(container) *8",
       "legendFormat": "Outflow:{{ container }}"
      }
     ]
    },
    {
     "title": "Microservices (Container Name) Overall CPU Cores Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$origin_prometheus\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "CPU Limitations：{{ container}}"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)",
       "legendFormat": "CPU Core Usage：{{ container}}"
      }
     ]
    },
    {
     "title": "Microservices (Container Name) Overall Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "Memory Limit：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "RSS：{{ container }}"
      }
     ]
    },
    {
     "title": "Microservice (Container Name) Pod Number",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 214 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container,namespace)",
       "legendFormat": "{{namespace}}：{{ container }}"
      }
     ]
    }
   ]
  }
 ]
}