{
 "title": "Kubernetes Cluster Dashboard with Deployment",
 "description": "Simple dashboard for observing your Kubernetes Deployment CPU and Memory usage.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_status_observed_generation{namespace=\"$namespace\", cluster=\"$cluster\"},deployment)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits{namespace=\"$namespace\", cluster=\"$cluster\", resource=\"cpu\", pod=~\"$deployment-.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment CPU and Memory Usage Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Deployment CPU Usage",
   "type": "timeseries",
   "description": "All pods CPU usage combined for selected deployment",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", cluster=\"$cluster\", resource=\"cpu\", pod=~\"$pod\"}) by (deployment)",
     "legendFormat": "$deployment - limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", cluster=\"$cluster\", resource=\"cpu\", pod=~\"$pod\"}) by (deployment)",
     "legendFormat": "$deployment  - request"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", cluster=\"$cluster\", pod=~\"$deployment.*\"}[$__rate_interval])) by (deployment)",
     "legendFormat": "$deployment  - usage"
    }
   ]
  },
  {
   "title": "Deployment Memory Usage",
   "type": "timeseries",
   "description": "All pods memory usage combined for selected deployment",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", cluster=\"$cluster\", resource=\"memory\", pod=~\"$pod\"}) by (deployment)",
     "legendFormat": "$deployment - limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", cluster=\"$cluster\", resource=\"memory\", pod=~\"$pod\"}) by (deployment)",
     "legendFormat": "$deployment  - request"
    },
    {
     "expr": "max(container_memory_usage_bytes{namespace=\"$namespace\", cluster=\"$cluster\", pod=~\"$pod\"}) by (deployment)",
     "legendFormat": "$deployment  - usage"
    }
   ]
  },
  {
   "title": "Number of Running Pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_ready{cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"${deployment:regex}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Desired Pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{\n  cluster=\"$cluster\",\n  namespace=\"$namespace\",\n  deployment=~\"${deployment:regex}\"\n}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unavailable Pod",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_unavailable{cluster=\"$cluster\", namespace=\"$namespace\", deployment=~\"${deployment:regex}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Resource Usage Summary - $pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "repeat": "pod"
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "All pods CPU usage combined for selected deployment",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", cluster=\"$cluster\", resource=\"cpu\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "$pod - limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", cluster=\"$cluster\", resource=\"cpu\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "$pod  - request"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", cluster=\"$cluster\", pod=~\"$pod.*\"}[$__rate_interval])) by (pod)",
     "legendFormat": "$pod  - usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "All pods memory usage combined for selected deployment",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(kube_pod_container_resource_limits{namespace=\"$namespace\", cluster=\"$cluster\", resource=\"memory\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod - limit"
    },
    {
     "expr": "max(kube_pod_container_resource_requests{namespace=\"$namespace\", cluster=\"$cluster\", resource=\"memory\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod  - request"
    },
    {
     "expr": "max(container_memory_working_set_bytes{namespace=\"$namespace\", cluster=\"$cluster\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod  - usage"
    }
   ]
  }
 ]
}