stages:
  - build
  - sonar
  - deploy
  - trigger_argo

image-build:
  stage: build
  image: registry.cloudaes.com/base-images/docker:24.0.5-cli
  resource_group: main
  services:
    - docker:24.0.5-dind
  variables:
    TZ: "Asia/Dhaka"
    LC_TIME: "en_US.UTF-8"
  before_script:
    - apk add --no-cache tzdata git libc6-compat curl bash
    - ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
    - echo "$TZ" > /etc/timezone
  script:
    - |
      /bin/bash <<'EOF'
        set -x
        set -e
        send_notification() {
          local payload="{\"text\": \"[$CI_PROJECT_NAME][$CI_COMMIT_REF_NAME][$1] $2 - Job: $CI_JOB_NAME, Tag: ${IMAGE_TAG:-empty}\"}"
          curl -s -X POST -H "Content-Type: application/json" -d "$payload" "$GOOGLE_CHAT_WEBHOOK_URL" || echo "Failed to send notification"
        }
        echo "Starting Docker build...";
        IMAGE_NAME="registry.cloudaes.com/bmd-sales-fe/bmd-sales-fe_prod";
        IMAGE_TAG="$(date +'%d%b')-$CI_MERGE_REQUEST_IID";
        export IMAGE_NAME IMAGE_TAG CI_JOB_NAME GOOGLE_CHAT_WEBHOOK_URL;
        echo "Debug: IMAGE_NAME=$IMAGE_NAME, IMAGE_TAG=$IMAGE_TAG, CI_JOB_NAME=$CI_JOB_NAME";
        [ -n "$IMAGE_TAG" ] && [ "$IMAGE_TAG" != "-" ] || { echo "Error: Invalid IMAGE_TAG"; send_notification "FE Build Failure" "Back to the drawing board"; exit 1; };
        echo "$harborpass" | docker login registry.cloudaes.com -u "$harboruser" --password-stdin || { send_notification "Build Failure" "Who are you scammer! ðŸ˜± - Docker login failed"; exit 1; }
        docker build --no-cache --progress=plain --build-arg VITE_SALES_API_URL="$VITE_SALES_API_URL_MAIN" --build-arg VITE_OTEL_EXPORTER_OTLP_ENDPOINT="$VITE_OTEL_EXPORTER_OTLP_ENDPOINT" --build-arg VITE_OTEL_SERVICE_NAME="prod-bmdsalesfe" --build-arg SIGNOZ_USERNAME="$SIGNOZ_USERNAME" --build-arg SIGNOZ_PASSWORD="$SIGNOZ_PASSWORD" --build-arg NEXUS_AUTH_TOKEN="$NEXUS_AUTH_TOKEN" -t "$IMAGE_NAME:$IMAGE_TAG" . || { send_notification "FE Build Failure" "Who broke the build?"; exit 1; };
        docker tag "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest" || { send_notification "FE Build Failure" "Tagging failed"; exit 1; };
        docker push "$IMAGE_NAME:$IMAGE_TAG" || { send_notification "FE Build Failure" "Push failed"; exit 1; };
        docker push "$IMAGE_NAME:latest" || { send_notification "FE Build Failure" "Push failed for latest"; exit 1; };
        docker rmi "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest" || echo "Warning: Failed to remove images";
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_APPROVED != "true"'
      when: always
    - when: never
  tags:
    - prod

sonarqube-report:
  image:
    name: registry.cloudaes.com/base-images/sonar-node20:v2
  resource_group: main
  needs:
  - job: image-build
  stage: sonar
  allow_failure: true
  script:
    - echo "Prod SonarQube"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_APPROVED != "true"'
      when: on_success
    - when: never
  tags:
    - prod

update-manifest:
  stage: deploy
  image: registry.cloudaes.com/base-images/bitnami/git:latest
  resource_group: main
  variables:
    TZ: "Asia/Dhaka"
    LC_TIME: "en_US.UTF-8"
  before_script:
    - apt-get update && apt-get install -y curl bash tzdata
    - ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
    - echo "$TZ" > /etc/timezone
    - git config --global http.sslVerify false
    - git config --global user.email "devops@quickops.io"
    - git config --global user.name "GitLab CI"
  script:
    - |
      /bin/bash <<'EOF'
        set -x
        set -e
        send_notification() {
          local payload="{\"text\": \"[$CI_PROJECT_NAME][$CI_COMMIT_REF_NAME][$1] $2 - Job: $CI_JOB_NAME, Tag: ${IMAGE_TAG:-empty}\"}"
          curl -s -X POST -H "Content-Type: application/json" -d "$payload" "$GOOGLE_CHAT_WEBHOOK_URL" || echo "Failed to send notification"
        }
        MR_IID=$(git log -1 --pretty=%B | grep -oP 'See merge request .*!\K\d+');
        IMAGE_TAG="$(date +'%d%b')-$MR_IID";
        echo "Debug: IMAGE_TAG=$IMAGE_TAG, CI_JOB_NAME=$CI_JOB_NAME";
        export IMAGE_TAG;
        [ -n "$IMAGE_TAG" ] || { echo "Error: IMAGE_TAG is empty"; send_notification "FE Deploy Failure" "Something's fishy ðŸŸ"; exit 1; };
        git clone --branch main "https://${gituser}:${gitpass}@172.17.19.247/devops/bmd-manifests.git" || { send_notification "FE Deploy Failure" "We have a problem ðŸ›‘ - Git clone failed"; exit 1; };
        cd bmd-manifests;
        ls -l k8s/5.frontend.yaml || { echo "Error: Manifest file not found"; send_notification "FE Deploy Failure" "Deployment crash ðŸ™ˆ - Manifest file not found"; exit 1; };
        sed -i "s|image: registry.cloudaes.com/bmd-sales-fe/bmd-sales-fe_prod:.*|image: registry.cloudaes.com/bmd-sales-fe/bmd-sales-fe_prod:${IMAGE_TAG}|" k8s/5.frontend.yaml || { send_notification "FE Deploy Failure" "Deployment crash ðŸ™ˆ - Manifest update failed"; exit 1; };
        cat k8s/5.frontend.yaml || echo "Error: Failed to read manifest";
        git add k8s/5.frontend.yaml || { send_notification "FE Deploy Failure" "Rollback time ðŸ” - Git add failed"; exit 1; };
        git commit -m "Update frontend image to ${IMAGE_TAG}" || { send_notification "FE Deploy Failure" "Rollback time ðŸ” - Git commit failed"; exit 1; };
        git push origin main || { send_notification "Deploy Failure" "Uh oh, something broke! ðŸ”¨ - Git push failed"; exit 1; };
        send_notification "Pipeline Success" "Please wait 30s! Triggering ArgoCD ðŸŽ‰";
      EOF
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never
  tags:
    - prod
    
trigger_argo:
  image: registry.cloudaes.com/base-images/argocli:v2.6.15
  stage: trigger_argo
  needs:
    - update-manifest
  resource_group: main
  script:
    - APP="bmdsales-prod-ns"
    - argocd login $main_argo_url --username $argo_user --password $argo_pass --insecure
    - argocd app sync $APP
    - argocd app wait $APP
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"'
      when: on_success
    - when: never
  tags:
    - prod
