---
- name: Initialize Kubernetes Cluster
  hosts: masters
  become: yes
  gather_facts: yes
  vars_files:
    - ../group_vars/all/main.yml
    - ../group_vars/masters/main.yml
  
  roles:
    - kubeadm-init
    - etcd