apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: harbor-pull-secret
  namespace: dev-quickops
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbG91ZGFlcy5jb20iOnsidXNlcm5hbWUiOiJyb2JvdCRxdWlja29wcy1hdXRvbWF0aW9uIiwicGFzc3dvcmQiOiJhMllOemdWQ20xcWQ5aGdjTVhSeTdzM2V5emlKNVdmSCJ9fX0K
  # echo '{"auths":{"<REGISTRY_URL>":{"username":"<USERNAME>","password":"<PASSWORD>"}}}' > dockerconfig.json
  # cat dockerconfig.json | base64 -w 0

---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: mysql-secret
  namespace: dev-quickops
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "cm9vdHBhc3N3b3JkMTIzQQ=="
  MYSQL_USER: "cXVpY2tvcHN1c2Vy"
  MYSQL_PASSWORD: "Y1BPMzdoZDRCZnF1aWNrb3BzdXN5dQ=="
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: mysql-configmap
  namespace: dev-quickops
data:
  #MYSQL_DATABASE: "quickops"
  MAIL_DATABASE: "mail"
  QUICKOPS_DATABASE: "quickops"
