groups:
  - name: docker-container.rules
    rules:
      - alert: DockerContainerDown
        expr: absent(container_last_seen)
        for: 1m
        labels:
          severity: critical
          autoresolve: "true"
        annotations:
          summary: "Container {{ $labels.name }} is down"
          description: >
            Container '{{ $labels.name }}' may be down because it has not been seen in over 60 seconds this could indicate a crash or stop.