groups:
  - name: docker-container.rules
    rules:
      - alert: DockerContainerDown
        expr: (time() - container_last_seen{job="docker-containers"}) > 60
        for: 3m
        labels:
          severity: critical
          autoresolve: "true"
        annotations:
          summary: "Container {{ $labels.name }} is down"
          description: >
            Container '{{ $labels.name }}' from project '{{ $labels.container_label_com_docker_compose_project }}',
            service '{{ $labels.container_label_com_docker_compose_service }}' has not been seen in over 60 seconds.
            This could indicate a crash or stop.