---
- name: Check if kubeconfig exists locally
  ansible.builtin.stat:
    path: "../roles/kubeconfig-fetch/files/kubeconfig/config"
  delegate_to: localhost
  register: kubeconfig_check
  run_once: true
  become: no

- name: Fetch kubeconfig from master node
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "../roles/kubeconfig-fetch/files/kubeconfig/config"
    flat: yes
  when: not kubeconfig_check.stat.exists
  run_once: true

- name: Verify kubeconfig was successfully fetched
  ansible.builtin.stat:
    path: "../roles/kubeconfig-fetch/files/kubeconfig/config"
  delegate_to: localhost
  register: kubeconfig_verify
  run_once: true
  become: no

  
- name: Show kubeconfig location and status
  ansible.builtin.debug:
    msg: "Kubeconfig {% if kubeconfig_verify.stat.exists %}successfully{% else %}failed to{% endif %} fetch to: {{ playbook_dir }}/roles/kubeconfig-fetch/files/kubeconfig/config"
  run_once: true