stages:
  - sonar
  - build
  - deploy
  - trigger_argo

sonarqube-analysis:
  image: registry.cloudaes.com/base-images/maven:3.9.9-eclipse-temurin-21
  stage: sonar
  resource_group: stage
  allow_failure: true
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  script:
    - mvn clean install -DskipTests=true sonar:sonar -Dsonar.projectKey=bmd-sales-be-dev -Dsonar.projectName=BMD-Sales-Backend-Dev -Dsonar.host.url=$SONAR_URL -Dsonar.token=$SONAR_TOKEN
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_APPROVED != "true"'
      when: always
    - when: never
  cache:
    paths:
      - .m2/repository
  tags:
    - dev

image-build:
  stage: build
  image: registry.cloudaes.com/base-images/aes-docker:24.0.5-cli
  needs:
    - sonarqube-analysis
  resource_group: stage
  services:
    - docker:24.0.5-dind
  script:
    - |
      /bin/bash <<'EOF'
        set -x
        set -e
        send_notification() {
          local payload="{\"text\": \"[$CI_PROJECT_NAME][$CI_COMMIT_REF_NAME][$1] $2 - Job: $CI_JOB_NAME, Tag: ${IMAGE_TAG:-empty}\"}"
          curl -s -X POST -H "Content-Type: application/json" -d "$payload" "$GOOGLE_CHAT_WEBHOOK_URL" || echo "Failed to send notification"
        }
        echo "Starting Docker build...";
        IMAGE_NAME="registry.cloudaes.com/bmd-sales-be/bms_sales_be";
        IMAGE_TAG="$(date +'%d%b')-$CI_MERGE_REQUEST_IID";
        export IMAGE_NAME IMAGE_TAG CI_JOB_NAME GOOGLE_CHAT_WEBHOOK_URL;
        echo "IMAGE_NAME=$IMAGE_NAME, IMAGE_TAG=$IMAGE_TAG";
        [ -n "$IMAGE_TAG" ] && [ "$IMAGE_TAG" != "-" ] || { echo "Error: Invalid IMAGE_TAG"; send_notification "BE Build Failure" "Back to the drawing board"; exit 1; };
        echo "$harborpass" | docker login registry.cloudaes.com -u "$harboruser" --password-stdin || { send_notification "BE Build Failure" "Registry Login Failed😱"; exit 1; }
        docker build --no-cache --build-arg NEXUS_USER=$NEXUS_USER --build-arg NEXUS_PASS=$NEXUS_PASS --build-arg BRANCH=$CI_MERGE_REQUEST_TARGET_BRANCH_NAME -t "$IMAGE_NAME:$IMAGE_TAG" -f dockerfiles/Dockerfile . || { send_notification "BE Build Failure" "Who broke the build?"; exit 1; };
        docker tag "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest" || { send_notification "FE Build Failure" "Tagging failed"; exit 1; };
        docker push "$IMAGE_NAME:$IMAGE_TAG" || { send_notification "BE Build Failure" "Image Push failed"; exit 1; };
        docker push "$IMAGE_NAME:latest" || { send_notification "BE Build Failure" "Image Push failed for latest"; exit 1; };
        docker rmi "$IMAGE_NAME:$IMAGE_TAG" "$IMAGE_NAME:latest" || echo "Warning: Failed to remove images";
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_APPROVED != "true"'
      when: on_success
    - when: never
  tags:
    - dev

update-manifest:
  stage: deploy
  image: registry.cloudaes.com/base-images/aes-git:v1.0.2
  resource_group: stage
  script:
    - |
      /bin/bash <<'EOF'
        set -x
        set -e
        send_notification() {
          local payload="{\"text\": \"[$CI_PROJECT_NAME][$CI_COMMIT_REF_NAME][$1] $2 - Job: $CI_JOB_NAME, Tag: ${IMAGE_TAG:-empty}\"}"
          curl -s -X POST -H "Content-Type: application/json" -d "$payload" "$GOOGLE_CHAT_WEBHOOK_URL" || echo "Failed to send notification"
        }
        MR_IID=$(git log -1 --pretty=%B | grep -oP 'See merge request .*!\K\d+');
        IMAGE_TAG="$(date +'%d%b')-$MR_IID";
        echo "IMAGE_TAG=$IMAGE_TAG, CI_JOB_NAME=$CI_JOB_NAME";
        export IMAGE_TAG;
        [ -n "$IMAGE_TAG" ] || { echo "Error: IMAGE_TAG is empty"; send_notification "BE Deploy Failure" "Something's fishy 🐟"; exit 1; };
        git clone --branch dev "https://${gituser}:${gitpass}@172.17.19.247/devops/bmd-manifests.git" || { send_notification "BE Deploy Failure" "We have a problem 🛑 - Git clone failed"; exit 1; };
        cd bmd-manifests;
        ls -l k8s/4.backend.yaml || { echo "Error: Manifest file not found"; send_notification "BE Deploy Failure" "Deployment crash 🙈 - Manifest file not found"; exit 1; };
        sed -i "s|image: registry.cloudaes.com/bmd-sales-be/bms_sales_be:.*|image: registry.cloudaes.com/bmd-sales-be/bms_sales_be:${IMAGE_TAG}|" k8s/4.backend.yaml || { send_notification "BE Deploy Failure" "Deployment crash 🙈 - Manifest update failed"; exit 1; };
        cat k8s/4.backend.yaml || echo "Error: Failed to read manifest";
        git add k8s/4.backend.yaml || { send_notification "BE Deploy Failure" "Rollback time 🔁 - Git add failed"; exit 1; };
        git commit -m "Update backend image to ${IMAGE_TAG}" || { send_notification "BE Deploy Failure" "Rollback time 🔁 - Git commit failed"; exit 1; };
        git push origin dev || { send_notification "Deploy Failure" "Uh oh, something broke! 🔨 - Git push failed"; exit 1; };
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "stage"'
      when: always
    - when: never
  tags:
    - dev

trigger_argo:
  image: registry.cloudaes.com/base-images/argocli:v2.6.15
  needs:
    - update-manifest
  resource_group: stage
  stage: trigger_argo
  script:
    - APP="bmdsales-dev-ns"
    - argocd login $dev_argo_url --username $argo_user --password $argo_pass --insecure
    - argocd app sync $APP
    - argocd app wait $APP
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "stage"'
      when: on_success
    - when: never
  tags:
    - dev
