kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-org-cm
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  org-log.conf: |-

    <source>
      @type tail
      format none
      path /var/log/org-*.log
      pos_file /var/log/org-*.log.pos
      read_from_head true
      tag org
    </source>


    <source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/es-containers.log.pos
      tag test
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    
    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level info
      type_name _doc
      include_tag_key true
      host elasticsearch.default.svc.cluster.local
      port 9200
      logstash_format true
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 10
        chunk_limit_size 2M
        queue_limit_length 8
        overflow_action block
      </buffer>
    </match>