apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment-1
  namespace: ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-1
  template:
    metadata:
      labels:
        app: mysql-1
    spec:
      containers:
      - name: mysql-1
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: your-root-password
          - name: MYSQL_DATABASE
            value: your-database-name
          - name: MYSQL_USER
            value: your-mysql-user
          - name: MYSQL_PASSWORD
            value: your-mysql-password
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service-1
  namespace: ns
spec:
  selector:
    app: mysql-1
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
