apiVersion: v1
data:
 app-password: akI1TzdSeE9UZWZmTGw5RTdKcVNMdE5HUks0dml1MTNGNUxQT2s3dC8zMD0=
 replication-password: L210b0ZJR0hFTjdDY3M3NndabkJ4ZzkveE94MTI1a3d5YU5sS3ZwbXdlST0=
 root-password: SFZxV0hFRDJ0MnJVY2NnMFAzeXAyMGtpaWg0QXh1OVQ5TG1YTHdQWWlBUT0=
kind: Secret
metadata:
  name: mysql-secret
  namespace: db-proxysql-prod
type: Opaque
---
apiVersion: v1
data:
  admin-password: eGhqbHNmd3R6UFZnQWNLanN2cXBla3phcE9YQzhZTjZ1VVhVSFB0T1Z3ND0=
  monitor-password: UWMyQ05NTDYweGxtTE1jZUtpNHZQc1pWdGlDZEVBcXhWeURjS2dIWWZxOD0=
kind: Secret
metadata:
  name: proxysql-secret
  namespace: db-proxysql-prod
type: Opaque