apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: db-proxysql-prod
data:
  primary.cnf: |
    [mysqld]
    log-bin=mysql-bin
    server-id=1
    gtid_mode=ON
    enforce_gtid_consistency=ON
  replica.cnf: |
    [mysqld]
    server-id=2
    read_only=ON
    gtid_mode=ON
    enforce_gtid_consistency=ON
    super_read_only=ON
  # These are now just templates
  setup-users.sql.template: |
    CREATE USER IF NOT EXISTS 'repl_user'@'%' IDENTIFIED BY '{{.MYSQL_REPLICATION_PASSWORD}}';
    GRANT REPLICATION SLAVE ON *.* TO 'repl_user'@'%';
    CREATE USER IF NOT EXISTS 'monitor'@'%' IDENTIFIED BY '{{.PROXYSQL_MONITOR_PASSWORD}}';
    GRANT SELECT ON *.* TO 'monitor'@'%';
    FLUSH PRIVILEGES;
  setup-replication.sql.template: |
    CHANGE REPLICATION SOURCE TO
      SOURCE_HOST='mysql-write.db-proxysql-prod.svc.cluster.local',
      SOURCE_PORT=3306,
      SOURCE_USER='repl_user',
      SOURCE_PASSWORD='{{.MYSQL_REPLICATION_PASSWORD}}',
      SOURCE_AUTO_POSITION=1;
    START REPLICA;
---
apiVersion: v1
data:
  .my.cnf: |
    [client]
    user=root
    password=HVqWHED2t2rUccg0P3yp20kiih4Axu9T9LmXLwPYiAQ=
    host=127.0.0.1
    port=3306
kind: ConfigMap
metadata:
  name: mysqld-exporter-config
  namespace: db-proxysql-prod