apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: db-proxysql-prod
  labels:
    app: mysql
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-write
  namespace: db-proxysql-prod
  labels:
    app: mysql
    tier: write
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
    statefulset.kubernetes.io/pod-name: mysql-0
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: db-proxysql-prod
  labels:
    app: mysql
    tier: read
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
    statefulset.kubernetes.io/pod-name: mysql-1