apiVersion: v1
kind: ConfigMap
metadata:
  name: proxysql-config
  namespace: db-proxysql-prod
data:
  proxysql.cnf: |
    datadir="/var/lib/proxysql"
    admin_variables=
    {
      admin_credentials="admin:$PROXYSQL_ADMIN_PASSWORD"
      mysql_ifaces="0.0.0.0:6032"
    }
    mysql_variables=
    {
      threads=8
      max_connections=4096
      default_query_delay=0
      default_query_timeout=36000000
      have_compress=true
      poll_timeout=2000
      interfaces="0.0.0.0:6033"
      default_schema="information_schema"
      stacksize=1048576
      server_version="8.0"
      connect_timeout_server=3000
      monitor_username="monitor"
      monitor_password="$PROXYSQL_MONITOR_PASSWORD"
      monitor_history=600000
      monitor_connect_interval=60000
      monitor_ping_interval=10000
      monitor_read_only_interval=1500
      monitor_read_only_timeout=500
    }
