apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: quickopsmail-config
  namespace: prod-quickops
data:
  spring_jpa_hibernate_ddl_auto: "update"
  db_host: "mysql"
  db_port: "3306"
  db_name: "mail"

---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: quickopsmail-secret
  namespace: prod-quickops
type: Opaque
data:
  db-username: cXVpY2tvcHN1c2Vy                # base64 encoded "quickopsuser"
  db-password: c014QTlUdEZDNzU5eFlvbnE4VDk= 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  namespace: prod-quickops 
  name: quickopsmail
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: quickopsmail
  template:
    metadata:
      labels:
        app: quickopsmail
    spec:
      imagePullSecrets:
      - name: harbor-pull-secret
      containers:
      - name: quickopsmail
        image: registry.cloudaes.com/quickops-mail/aes-comm-sys-be:18May-15-06-6bcbe5a
        ports:
          - containerPort: 9090
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: quickopsmail-secret
                key: db-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: quickopsmail-secret
                key: db-password
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            valueFrom:
              configMapKeyRef:
                name: quickopsmail-config
                key: spring_jpa_hibernate_ddl_auto
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: quickopsmail-config
                key: db_host
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: quickopsmail-config
                key: db_port
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: quickopsmail-config
                key: db_name
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  namespace: prod-quickops
  name: quickopsmail-service
spec:
  selector:
    app: quickopsmail
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP