apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: expense-tracker
type: Opaque
data:
  postgres-user: cG9zdGdyZXM= # postgres
  postgres-password: c3Ryb25nUGFzc3dvcmQxMjM0 # strongPassword1234
  db-username: YXBwbGljYXRpb251c2Vy # applicationuser
  db-password: YXBwbGljYXRpb25QYXNzNDMyMQ== # applicationPass4321