apiVersion: v1
kind: Service
metadata:
  name: postgresdb-exporter
  namespace: exporters
  labels:
    app: postgresdb-exporter
spec:
  selector:
    app: postgresdb-exporter
  ports:
  - port: 9187
    targetPort: http
    name: http