---
- name: restart calico-node
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: "calico-node-restart-{{ ansible_date_time.epoch }}"
        namespace: kube-system
        labels:
          app: calico-node-restart
      spec:
        containers:
        - name: restart
          image: busybox
          command: ["sh", "-c", "sleep 10 && kubectl delete pod -l k8s-app=calico-node -n kube-system"]
  delegate_to: "{{ groups['masters'][0] }}"