apiVersion: apps/v1
kind: Deployment
metadata:
  name: goal-fe
  labels:
    app: goal-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goal-fe
  template:
    metadata:
      labels:
        app: goal-fe
    spec:
      containers:
      - name: goal-fe
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: ecr-secret



#kubectl create secret docker-registry ecr-secret --docker-server=699475925713.dkr.ecr.ap-south-1.amazonaws.com --docker-username=AWS --docker-password=$(aws ecr get-login-password --region ap-south-1) --docker-email=test.com
