concurrent = 1
check_interval = 0
connection_max_age = "10m0s"
shutdown_timeout = 0
log_level = "warning"

[session_server]
  session_timeout = 1800

[[runners]]
  name = "gitlab-runner-1"
  url = "gitlab.kk.host"  # change to your GitLab instance URL
  executor = "docker"
  token = "glrt-t1_Y8kCz__UFCyLchnFixv3"  # add your registration token here
  limit = 0
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
  [runners.cache]
    Insecure = false
