---
# Master Node Configuration
kubernetes_role: "master"
etcd_cluster: true

# High Availability Configuration
control_plane_endpoint: "172.17.17.19"
keepalived_virtual_ip: "172.17.17.19"
keepalived_interface: "eth0"

# kubeadm Configuration
kubeadm_init_extra_args: ""
kubeadm_join_extra_args: ""

# etcd Configuration for Masters
etcd_initial_cluster: >
  master1=https://172.17.17.19:2380,
  master2=https://172.17.17.20:2380

# Resource Limits
kube_apiserver_cpu_requests: "200m"
kube_apiserver_memory_requests: "300Mi"
kube_apiserver_cpu_limits: "400m"
kube_apiserver_memory_limits: "600Mi"
kube_controller_manager_cpu_requests: "200m"
kube_controller_manager_memory_requests: "400Mi"
kube_scheduler_cpu_requests: "200m"
kube_scheduler_memory_requests: "256Mi"
etcd_cpu_requests: "300m"
etcd_memory_requests: "300Mi"

# Security
kube_apiserver_cert_extra_sans:
  - "192.168.1.100"
  - "k8s-api.example.com"