apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  namespace: trace-quickops
  name: quickopsbe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickopsbe
  template:
    metadata:
      labels:
        app: quickopsbe
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: quickopsbe
          image: registry.cloudaes.com/quickops-be/quickopsbe:opentelemetryv7
          ports:
            - containerPort: 8083
            - containerPort: 5583  # Debug port
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DB
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: QUICKOPS_DATABASE
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://172.17.18.251:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: OTEL_SAMPLER_PROBABILITY
              value: "1.0"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=quickopsbe-app
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  namespace: trace-quickops
  name: quickopsbe-service
spec:
  selector:
    app: quickopsbe
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: debug
      protocol: TCP
      port: 5583
      targetPort: 5583
      nodePort: 31583
